name: Build & Deploy .NET to ACR with Sliplane

on:
  workflow_dispatch:

env:
  ACR_NAME: mybsacr.azurecr.io
  IMAGE_NAME: sliplane-dotnet
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login $ACR_NAME -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t $ACR_NAME/${IMAGE_NAME}:${IMAGE_TAG} ./dotnet-app
          docker push $ACR_NAME/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Trigger Sliplane Webhook Deployment
        run: |
          curl -X GET "https://app.sliplane.io/webhook/service_45oq4xwbjxzq"
