name: Build & Deploy .NET to ACR

on:
  workflow_dispatch:

env:
  ACR_NAME: mybsacr.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login $ACR_NAME -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build & Push .NET App
        run: |
          docker build -t $ACR_NAME/sliplane-dotnet:${IMAGE_TAG} .
          docker push $ACR_NAME/sliplane-dotnet:${IMAGE_TAG}
